### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by oboingo** [ambitioninc/django-entity#107]
Can I get some guidance on using django-entity with permissions?  I have certain users I wan't to be able to access resources, but only on pre-defined entities.  Ideally, there would be some user-defined profiles, (say, manager, user, etc) that have permissions assigned to them, and then that user+profile+entity becomes a combo.  So if that user has a user profile/group assigned to them then they can access certain aspects of an entity, but if they have manager profile, then perhaps different things.  How, in general, would you accomplish this?  I don't need you to write all the code (but I certainly wouldn't turn it down!), just a some general pointers would be great.

**Comment by wesleykendall** [comment]
I don't think Github issues are the appropriate place to be asking advice on how to structure permissions for your app. You'll get better advice on stackoverflow.com

**Comment by oboingo** [comment]
Agreed.  I even mentioned that in my email to the authors, with no reply, several weeks ago.  Not trying to be a pain, was just looking for some general advice in how it relates to this specific app.  A pointer to some documentation, or Discord/IRC/etc, forums for the app or wherever some questions could be answered.  Do the devs look at stackoverflow for questions related to django-entity?  (Just afraid that my question would get lost in the noise)
